apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: isv-must-gather-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MustGather is the Schema for the mustgathers API
      displayName: Must Gather
      kind: MustGather
      name: mustgathers.isv.operator.com
      specDescriptors:
      - description: MustGatherImgURL is the ISV operator must gather image url
        displayName: ISV Operator Must-Gather Image URL
        path: mustGatherImgURL
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:string
        - urn:alm:descriptor:io.kubernetes:custom
      version: v1alpha1
  description: This provide the easy way to gather debugging data of ISV Operator.
  displayName: ISV Must Gather Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - mustgather
  - isv
  - managed service
  links:
  - name: Isv Must Gather Operator
    url: https://isv-must-gather-operator.domain
  maintainers:
  - email: jlee@redhat.com
    name: jay
  maturity: alpha
  provider:
    name: Jooho Lee
    url: https://github.com/Jooho
  version: 0.0.0
